os: linux
dist: xenial

language: node_js

node_js:
- '12.0'

cache:
- npm

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


install:
  - npm install

script:
  - npm run build -- --prod
  #- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

before_deploy: 
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - aws s3 rm s3://static.kbharkiv.dk/correctocr/  --recursive # empty destination folder in S3 bucket

deploy:
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: static.kbharkiv.dk
    cache_control: 'no-cache'
    local_dir: dist
    upload_dir: correctocr
    acl: public_read
    region: eu-west-1
    on:
      repo: CopenhagenCityArchives/CorrectOCR-frontend
      branch: master
    edge: true
    cleanup: false