language: node_js

node_js:
- '11.9'

cache:
- npm

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

deploy:
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: static.kbharkiv.dk
    cache_control: 'no-cache'
    local_dir: dist
    upload_dir: correctocr
    acl: public_read
    region: eu-west-1
    on:
      repo: CopenhagenCityArchives/CorrectOCR-frontend
      branch: master
    edge: true
    cleanup: false